#ifndef NOPCONSOLE_H
#define NOPCONSOLE_H

//RcB: SKIPON "CONSOLE_BACKEND=SDL_CONSOLE"
//RcB: SKIPON "CONSOLE_BACKEND=NCURSES_CONSOLE"
//RcB: SKIPON "CONSOLE_BACKEND=TERMBOX_CONSOLE"
//RcB: DEP "nopconsole.c"
//RcB: SKIPOFF "CONSOLE_BACKEND=SDL_CONSOLE"
//RcB: SKIPOFF "CONSOLE_BACKEND=NCURSES_CONSOLE"
//RcB: SKIPOFF "CONSOLE_BACKEND=TERMBOX_CONSOLE"

typedef struct NopConsole {
	int dummy;
} NopConsole;

#endif
